# Generated by Django 4.2.29 on 2026-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studydocument',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
